language: python
services:
  - docker
python:
  - "3.6"
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_push
  - make test_xunit
deploy:
  provider: heroku
  app: calm-inlet-96846
  api_key: ${HEROKU_API_KEY}
